import {
  tablerAlphabetKorean,
  tablerBike,
  tablerBrandWindows,
  tablerCalendar,
  tablerChevronDown,
  tablerChevronUp,
  tablerCloudDown,
  tablerCloudDownload,
  tablerCreditCard,
  tablerLogout,
  tablerNote,
  tablerPhoto,
  tablerRefresh,
  tablerSettingsCode,
  tablerSquareX,
  tablerTemperatureSun,
  tablerX,
} from '@ng-icons/tabler-icons';

export const icons = {
  tablerBike,
  tablerTemperatureSun,
  tablerAlphabetKorean,
  tablerNote,
  tablerCalendar,
  tablerCreditCard,
  tablerChevronUp,
  tablerChevronDown,
  tablerX,
  tablerPhoto,
  tablerRefresh,
  tablerSquareX,
  tablerLogout,
  tablerCloudDown,
  tablerCloudDownload,
  tablerBrandWindows,
  tablerSettingsCode,
};
